### ISSUE TITLE
require 即报错

### ISSUE THREAD

**Issue by wong2** [jdcloud-api/jdcloud-sdk-nodejs#53]
```
> var JDCloud = require('jdcloud-sdk-js');
{ Error: Cannot find module './order'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18) code: 'MODULE_NOT_FOUND' }
```

**Comment by imshenshen** [comment]
@oulinbao 查一下生成SDK的逻辑？`src/services/all.js`应该和`src/services/`目录文件是对应，

比如`all.js`中引用了`order.js`，但是`src/services/`目录下没有order.js

**Comment by imshenshen** [comment]
@wong2 你可以临时先require你需要的service。比如`var NC = require('jdcloud-sdk-js/services/nativecontainer');`

**Comment by wong2** [comment]
@imshenshen 其实我想用的 service 这个 SDK 里还没有。。https://github.com/jdcloud-api/jdcloud-sdk-nodejs/issues/52 然后我是想试着自定义一个 service 使用的，然后就遇到这个报错

**Comment by imshenshen** [comment]
> @imshenshen 其实我想用的 service 这个 SDK 里还没有。。#52 然后我是想试着自定义一个 service 使用的，然后就遇到这个报错

已经反馈给相关业务线同学了，不建议自己改Service

**Comment by wong2** [comment]
谢谢，SDK里能有当然最好了

**Comment by Tanc009** [comment]
sdk已更新

**Comment by wong2** [comment]
谢谢
